depth_nodelet:
  type: gr_depth_processing/MyNodeletClass
  remappings: 
    color_info: /camera/color/camera_info
    depth_info: /camera/depth/camera_info
    color_frame: /camera/color/image_raw
    depth_frame: /camera/depth/image_rect_raw
    bounding_boxes: /darknet_ros/bounding_boxes
#depth_nodelet_2:
# type: gr_depth_processing/MyNodeletClass
#  remappings: 
#    color_info: /color_info2
#    depth_info: /depth_info2
#    color_frame: /depth_frame2
#    depth_frame: /depth_frame2
#    bounding_boxes: /bounding_boxes2
lidar_nodelet:
  type: gr_pointcloud_processing/PointCloudProcessor
  remappings: 
    global_frame: velodyne
