depth_nodelet:
  type: gr_depth_processing/MyNodeletClass
  remappings: 
    color_info: /camera/color/camera_info
    depth_info: /camera/depth/camera_info
    color_frame: /camera/color/image_raw
    depth_frame: /camera/depth/image_rect_raw
    bounding_boxes: /darknet_msgs/bounding_boxes
lidar_nodelet:
  type: gr_pointcloud_processing/PointCloudProcessor
  remappings: 
    global_frame: velodyne
