min_points:
  minval: 0
  maxval: 20
  default: 4
min_canny:
  minval: 0
  maxval: 255
  default: 110
max_canny:
  minval: 0
  maxval: 255
  default: 150
rho:
  minval: 1
  maxval: 10
  default: 1
hough_threshold:
  minval: 1
  maxval: 100
  default: 5
hough_min_len:
  minval: 1
  maxval: 200
  default: 33
hough_gap:
  minval: 1
  maxval: 100
  default: 5
hough_degrees:
    minval: 1
    maxval: 180
    default: 180
dilation_shape:
  minval: 0
  maxval: 2
  default: 0
dilation_size:
  minval: 1
  maxval: 10
  default: 3
erosion_shape:
  minval: 0
  maxval: 2
  default: 2
erosion_size:
  minval: 1
  maxval: 10
  default: 1
erode_enable:
  minval: 0
  maxval: 1
  default: 0
dilate_enable:
  minval: 0
  maxval: 1
  default: 0
l_parallel_threshold:
  minval: 0
  maxval: 31416
  default: 2500
r_parallel_threshold:
  minval: 0
  maxval: 31416
  default: 2500
hue_min:
  minval: 0
  maxval: 255
  default: 55
hue_max:
  minval: 0
  maxval: 255
  default: 100
saturation_min:
  minval: 0
  maxval: 255
  default: 0
saturation_max:
  minval: 0
  maxval: 255
  default: 50
value_min:
  minval: 0
  maxval: 255
  default: 0
value_max:
  minval: 0
  maxval: 255
  default: 255
entropy_disk:
  minval: 0
  maxval: 20
  default: 1
roi_points:
  x0: [250, 250]
  x1: [400, 250]
  x2: [500, 500]
  x3: [150, 500]
