min_points:
  minval: 0
  maxval: 20
  default: 5
min_canny:
  minval: 0
  maxval: 255
  default: 80
max_canny:
  minval: 0
  maxval: 255
  default: 150
rho:
  minval: 1
  maxval: 10
  default: 1
hough_threshold:
  minval: 1
  maxval: 100
  default: 10
hough_min_len:
  minval: 1
  maxval: 200
  default: 25
hough_gap:
  minval: 1
  maxval: 100
  default: 10
erosion_shape:
  minval: 0
  maxval: 2
  default: 1
erosion_size:
  minval: 1
  maxval: 3
  default: 2
erosion_enable:
  minval: 0
  maxval: 1
  default: 0
parallel_threshold:
  minval: 0
  maxval: 31416
  default: 450
roi_points:
  x0: [280, 200]
  x1: [400, 200]
  x2: [500, 500]
  x3: [150, 500]
